### PR TITLE
Change .paged() to .asPaged() throughout

### PR DESCRIPTION
**Pull request by jimallman**
This matches the current plugin implementation and should avoid confusion for newcomers.

### CODE REVIEW

**Comment by lelandrichardson** [comment]
Great, Thanks!

**Comment by jimallman** [comment]
This is a great plugin, by the way. I had to tweak the knockout-mapping plugin to use paged observableArrays by default, but now they're working together well.

**Comment by lelandrichardson** [comment]
Thanks!

I'd be interested in seeing the code you wrote to modify the knockout-mapping plugin...

I've written a couple of other extensions that handle constructor-based observables which I would love to make compatible with the knockout-mapping plugin.

**Comment by jimallman** [comment]
It's tricky, because while the mapping plugin is very flexible about most elements, arrays are uniformly turned into `observableArray`s. I hacked the line where this occurs to assume the existence of your paging plugin, so instead of this:

```
    mappedRootObject = ko.observableArray([]);
```

..it does this:

```
    mappedRootObject = ko.observableArray([]).asPaged(20);
```

This is a nasty kludge, and it should at least check for the existence of the `asPaged` method first. A better solution might be a new option for the mapping plugin that asserts a non-standard default mapping for all arrays. Or possibly a way of specifying arrays properly in the normal mapping options.

**Pull request merged**
